name: "CI and Doc"
on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        python-version: [3.7, 3.8]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Set up Python ${{ matrix.python-version }} 🔧
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies 🔧
      run: |
        python -m pip install --upgrade pip
        pip install -e .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set up Python 🔧
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install -U sphinx sphinx-gallery kaleido sphinx_bootstrap_theme numpydoc xlrd==1.2.0
          pip install -e .

      - name: Build the Doc 🔧
        run: |
          cd docs
          make html
          touch build/html/.nojekyll

      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs/build/html/
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
